### ISSUE TITLE
Proposed documentation structure

### ISSUE THREAD

**Issue by Photosynthesis** [MurmurationsNetwork/MurmurationsDocumentation#1]
Here's a proposed structure for the docs. It's similar to the top-level structure that's in the repo, except that there's an added 'introduction' section, and the 'architecture' section is removed as a top-level section, with the architecture content included elsewhere. @geoffturk and @olisb please comment if you see things that should be changed about this! Otherwise I will proceed to implement. The structure can also be changed later without too much difficulty.

Introduction 

- Why Murmurations?
- Basic architecture (including diagrams)

Guides

- For nodes: put your project on the map
    - Using MPG
    - Host your own data
    - Use the WP plugin
- For aggregators: map your sector, area, or network
    - Creating a schema
    - Running an aggregator
    - Collecting data
- For data holders: share data into the Murmurations ecosystem
    - Schema options
    - Endpoint options
    

Technical documentation

- Index API reference
- Overview of Murmurations repos and codebase
- Murmurations Wordpress aggregator plugin
    - React interfaces
- Wordpress node plugin
- Murmurations Profile Generator (MPG)

Getting support

Contributing

Road map

FAQ

**Comment by olisb** [comment]
This looks like a great start to me! There will always  be changes and additions but we can  slot those in as we go...
